// Test Card data
import Card from './card'

export const aceOfClubs = new Card('Ace', 'Clubs', 14, 'AC')
export const kingOfClubs = new Card('King', 'Clubs', 13, 'KC')
export const sevenOfClubs = new Card(7, 'Clubs', 7, '7C')
export const fourOfClubs = new Card(4, 'Clubs', 4, '4C')
export const threeOfClubs = new Card(3, 'Clubs', 3, '3C')
export const twoOfClubs = new Card(2, 'Clubs', 2, '2C')

export const aceOfDiamonds = new Card('Ace', 'Diamonds', 14, 'AD')
export const kingOfDiamonds = new Card('King', 'Diamonds', 13, 'KD')
export const queenOfDiamonds = new Card('Queen', 'Diamonds', 12, 'QD')
export const jackOfDiamonds = new Card('Jack', 'Diamonds', 11, 'JD')
export const sevenOfDiamonds = new Card(7, 'Diamonds', 7, '7D')
export const threeOfDiamonds = new Card(3, 'Diamonds', 3, '3D')
export const twoOfDiamonds = new Card(2, 'Diamonds', 2, '2D')

export const aceOfHearts = new Card('Ace', 'Hearts', 14, 'AH')
export const queenOfHearts = new Card('Queen', 'Hearts', 12, 'QH')
export const sevenOfHearts = new Card(7, 'Hearts', 7, '7H')
export const sixOfHearts = new Card(6, 'Hearts', 6, '6H')
export const fiveOfHearts = new Card(5, 'Hearts', 5, '5H')
export const fourOfHearts = new Card(4, 'Hearts', 4, '4H')
export const threeOfHearts = new Card(3, 'Hearts', 3, '3H')
export const twoOfHearts = new Card(2, 'Hearts', 2, '2H')

export const aceOfSpades = new Card('Ace', 'Spades', 14, 'AS')
export const kingOfSpades = new Card('King', 'Spades', 13, 'KS')
export const queenOfSpades = new Card('Queen', 'Spades', 12, 'QS')
export const jackOfSpades = new Card('Jack', 'Spades', 11, 'JS')
export const tenOfSpades = new Card(10, 'Spades', 10, 'TS')
export const nineOfSpades = new Card(9, 'Spades', 9, '9S')
export const eightOfSpades = new Card(8, 'Spades', 8, '8S')
export const sixOfSpades = new Card(6, 'Spades', 6, '6S')
export const fiveOfSpades = new Card(5, 'Spades', 5, '5S')
export const fourOfSpades = new Card(4, 'Spades', 4, '4S')
export const threeOfSpades = new Card(3, 'Spades', 3, '3S')
export const twoOfSpades = new Card(2, 'Spades', 2, '2S')
